### PR TITLE
revert AppEngineException to checked

### LINKED ISSUE #84: Make AppEngineException checked
This indicates an unpredictable environmental condition, not a program bug. This is exactly what checked exceptions were designed for.

### PR DESCRIPTION
**Pull request by elharo**
@loosebazooka @chanseokoh fix #84

### CODE REVIEW

**Comment by chanseokoh** [comment]
I support the change.

There are check-style failures though.

**Comment by elharo** [comment]
This is what checkstyle is flagging:

```
      Runtime.getRuntime().addShutdownHook(new Thread(() -> deleteCopiedPython(pythonExePath)));
```

I think the lambda confuses it.

**Comment by elharo** [comment]
Running manually I see hundreds of checkstyle errors. Not clear why it's failing now.

**Comment by chanseokoh** [comment]
`mvn fmt:format` if you don't want to think about optimized styling.

File: src/main/java/com/google/cloud/tools/appengine/api/AppEngineException.java [hunk 1]
```diff
@@ -16,8 +16,8 @@
 
 package com.google.cloud.tools.appengine.api;
 
-/** API-level runtime exception for wrapping any failures in performing library operations. */
-public class AppEngineException extends RuntimeException {
+/** API-level exception for wrapping any failures in performing library operations. */
+public class AppEngineException extends Exception {
```
Comment (patflynn) [inline src/main/java/com/google/cloud/tools/appengine/api/AppEngineException.java]: do we need this exception at all?  When would you want to catch this instead of a more specific error that you can handle?

Comment (elharo) [reply src/main/java/com/google/cloud/tools/appengine/api/AppEngineException.java]: Right now there are about 20 places where we throw a raw AppEngineException instead of a subclass. Might be worth looking at making this abstract in another PR if we shouldn't be doing that.

**Comment by elharo** [comment]
Ping

**Comment by chanseokoh** [comment]
Are we agreed on removing the checkstyle from `pom.xml`?

File: pom.xml [hunk 2]
```diff
@@ -218,35 +218,6 @@
         </executions>
       </plugin>
 
-      <plugin>
```
Comment (loosebazooka) [inline pom.xml]: What was the motivation for removing this?

Comment (elharo) [reply pom.xml]: It was failing the build on Java 8 lambda constructs it didn't understand.

Comment (loosebazooka) [reply pom.xml]: I can't tell if we're running on different environments, but I only get these checkstyle warnings:
```
[WARNING] src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java:[298] (javadoc) NonEmptyAtclauseDescription: At-clause should have a non-empty description.
[WARNING] src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java:[344] (javadoc) NonEmptyAtclauseDescription: At-clause should have a non-empty description.
```

Comment (chanseokoh) [reply pom.xml]: Maybe something works differently on Travis. The following log is from the very first commit: 
4c2dee5

https://travis-ci.org/GoogleCloudPlatform/appengine-plugins-core/builds/351041235?utm_source=github_status&utm_medium=notification

```
[INFO] Building jar: /home/travis/build/GoogleCloudPlatform/appengine-plugins-core/target/appengine-plugins-core-0.5.2-SNAPSHOT-sources.jar
[INFO] com already added, skipping
[INFO] com/google already added, skipping
[INFO] com/google/cloud already added, skipping
[INFO] com/google/cloud/tools already added, skipping
[INFO] com/google/cloud/tools/libraries already added, skipping
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (google-checks) @ appengine-plugins-core ---
[WARNING] src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java:[298] (javadoc) NonEmptyAtclauseDescription: At-clause should have a non-empty description.
[WARNING] src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java:[344] (javadoc) NonEmptyAtclauseDescription: At-clause should have a non-empty description.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:47 min
[INFO] Finished at: 2018-03-08T21:50:22Z
[INFO] Final Memory: 41M/1556M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (google-checks) on project appengine-plugins-core: You have 2 Checkstyle violations. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by elharo** [comment]
At the command line it seems to run with sun_checks rather than google_checks:

```
elharo-macbookair99:appengine-plugins-core elharo$ mvn checkstyle:check
[INFO] Scanning for projects...
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/maven-metadata.xml (1.0 kB at 1.2 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/3.0.0/maven-checkstyle-plugin-3.0.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/3.0.0/maven-checkstyle-plugin-3.0.0.pom (15 kB at 175 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/3.0.0/maven-checkstyle-plugin-3.0.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/3.0.0/maven-checkstyle-plugin-3.0.0.jar (108 kB at 761 kB/s)
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building App Engine Plugins Core Library 0.5.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.0.0:check (default-cli) @ appengine-plugins-core ---
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-resources/1.1.0/plexus-resources-1.1.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-resources/1.1.0/plexus-resources-1.1.0.pom (3.2 kB at 47 kB/s)
Downloading: https://repo.maven.apache.org/maven2/com/puppycrawl/tools/checkstyle/6.18/checkstyle-6.18.pom
Downloaded: https://repo.maven.apache.org/maven2/com/puppycrawl/tools/checkstyle/6.18/checkstyle-6.18.pom (71 kB at 717 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/antlr/antlr4-runtime/4.5.3/antlr4-runtime-4.5.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/antlr/antlr4-runtime/4.5.3/antlr4-runtime-4.5.3.pom (2.3 kB at 38 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/antlr/antlr4-master/4.5.3/antlr4-master-4.5.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/antlr/antlr4-master/4.5.3/antlr4-master-4.5.3.pom (3.7 kB at 61 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-resources/1.1.0/plexus-resources-1.1.0.jar
Downloading: https://repo.maven.apache.org/maven2/com/puppycrawl/tools/checkstyle/6.18/checkstyle-6.18.jar
Downloading: https://repo.maven.apache.org/maven2/org/antlr/antlr4-runtime/4.5.3/antlr4-runtime-4.5.3.jar
Downloading: https://repo.maven.apache.org/maven2/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-resources/1.1.0/plexus-resources-1.1.0.jar (23 kB at 162 kB/s)
Downloaded: https://repo.maven.apache.org/maven2/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar (53 kB at 323 kB/s)
Downloaded: https://repo.maven.apache.org/maven2/org/antlr/antlr4-runtime/4.5.3/antlr4-runtime-4.5.3.jar (302 kB at 1.4 MB/s)
Downloaded: https://repo.maven.apache.org/maven2/com/puppycrawl/tools/checkstyle/6.18/checkstyle-6.18.jar (1.2 MB at 2.7 MB/s)
[INFO] There are 2616 errors reported by Checkstyle 6.18 with sun_checks.xml ruleset.
[ERROR] src/main/java/com/google/cloud/tools/managedcloudsdk/ProgressListener.java:[0] (javadoc) JavadocPackage: Missing package-info.java file.
[ERROR] 
...
```

**Comment by loosebazooka** [comment]
Yeah, if you run it from the command line, I don't think it's configured correctly. I think we need to restructure the plugin config a little, I added #570
