### PR TITLE
throw NullPointerException

### LINKED ISSUE #603: FilePermissions.verifyDirectoryCreatable is effectively nullable
and probably shouldn't be

### PR DESCRIPTION
**Pull request by elharo**
@loosebazooka fix #603

### CODE REVIEW

File: src/main/java/com/google/cloud/tools/io/FilePermissions.java [hunk 1]
```diff
@@ -41,6 +42,7 @@
   public static void verifyDirectoryCreatable(Path path)
       throws AccessDeniedException, NotDirectoryException {
 
+    Preconditions.checkNotNull(path, "Null directory path");
```
Comment (chanseokoh) [inline src/main/java/com/google/cloud/tools/io/FilePermissions.java]: Could add `@throws NPE` to the Javadoc.

Comment (elharo) [reply src/main/java/com/google/cloud/tools/io/FilePermissions.java]: We normally assume this by default and only document it if the argument is Nullable.
