### PR TITLE
Accept "HEAD" as CloudSdkVersion

### LINKED ISSUE #561: Deal with "HEAD" in cloud SDK versions.
Perhaps throwing an exception for this known case of the SDK isn't the ideal response.

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #561.

I should say this may not be an ideal way to deal with HEAD. I've wondered what `getMajorVersion()` etc should return for HEAD, and after some tries, I ended up assigning the max int limit to the individual elements. This has the following consequences.

- A HEAD is just another regular version, nothing special, only having high numbers that are unsurpassable.
- When comparing recency, HEAD is always later (greater) than any non-HEAD version, although in reality this will not hold in most cases.
- One HEAD version is semantically equal to another HEAD version, although this will not be true in reality in almost all cases.

And I also need to verify if the content of the `VERSION` file is exactly `HEAD` without any surplus space.

### CODE REVIEW

**Comment by loosebazooka** [comment]
You could trim the string if you're worried about spaces

**Comment by chanseokoh** [comment]
I added `trim()` just in case (although https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/561#issuecomment-397367152 shows it's precisely `HEAD`).

File: src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java [hunk 1]
```diff
@@ -52,22 +52,29 @@ public CloudSdkVersion(String version) {
...
-    if (!matcher.matches()) {
-      throw new IllegalArgumentException(
-          String.format("Pattern \"%s\" is not a valid CloudSdkVersion.", version));
-    }
-
-    majorVersion = Integer.parseInt(matcher.group("major"));
-    minorVerion = Integer.parseInt(matcher.group("minor"));
-    patchVersion = Integer.parseInt(matcher.group("patch"));
+    if ("HEAD".equals(version.trim())) {
+      majorVersion = Integer.MAX_VALUE;
```
Comment (elharo) [inline src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java]: Instead of faking a version number we could change the comparable logic to understand that HEAD is later than other versions.

**Comment by chanseokoh** [comment]
> Do we know why/when the VERSION file contains the string "HEAD"?

An internal dogfood version is one case, I'm reasonable sure. I don't know about any other case. If it is HEAD, at least it indicates that the SDK was not installed from official channels. So I believe this is for internal support.

So when first installing a dogfood version, it will be the latest one, but as new official releases roll out, the dogfood version will be out-dated until the user manually updates it. Currently, the user can't use our tools with a dogfood version at all, since we throw an exception with a version parsing error.

File: src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java (hunk 1 above)
Comment (chanseokoh) [reply src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java]: It's not a big deal to have such a dedicated logic, but we still have the question of which integer value to return when clients call `getMajorVersion()`, `getMinorVersion()`, and `getPatchVersion()`. And, we should also consider that clients may use these method to determine minimal versions, for example. That is,

```java
if (version.getMajorVersion() > 198
    || version.getMajorVersion() > 197 && version.getMinorVersion() > 3) {
   // minimum version requirement
}
```

Returning large values for HEAD seems not a terrible idea, as the main purpose as I understand is to unblock the internal users from using our tools by making the check for the minimum SDK version requirement pass.

Comment (chanseokoh) [reply src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java]: That said, another conceptually ideal way is to make `getMajorVersion()` and such return another layer of abstraction on top of `int` to include a special value for the HEAD notion, but considering that this is mainly for internal support (and maybe an SDK manually built from source, which would extremely rare), I don't think it's worth the complexity.

**Comment by briandealwis** [comment]
Maybe we should just get rid of the methods that expose the version fields.  So it's comparable, but that's it.

**Comment by patflynn** [comment]
That sounds pretty good to me. +1.

File: src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java [hunk 2]
```diff
@@ -142,7 +155,8 @@ public int compareTo(CloudSdkVersion other) {
 
   @Override
   public int hashCode() {
-    return Objects.hash(majorVersion, minorVerion, patchVersion, preRelease, buildIdentifier);
+    return Objects.hash(
```
Comment (briandealwis) [inline src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java]: Hmm, should we be hashing `version`?  Consider "0.0.1" vs "0.0.01": we previously considered them the same.

File: src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java [hunk 3]
```diff
@@ -164,24 +178,12 @@ public boolean equals(Object obj) {
     CloudSdkVersion otherVersion = (CloudSdkVersion) obj;
 
     return Objects.equals(majorVersion, otherVersion.majorVersion)
```
Comment (briandealwis) [inline src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java]: One advantage of using HEAD = { -1, -1, -1 } is that we can't create a version from "-1.-1.-1" whereas we could from "999999.999999.999999".

File: src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionTest.java [hunk 4]
```diff
@@ -71,49 +79,34 @@ public void testConstructor_missingRequiredNumbers() {
   @Test
   public void testConstructor_requiredNumbersOnly() {
     CloudSdkVersion version = new CloudSdkVersion("0.1.0");
-    assertEquals(0, version.getMajorVersion());
-    assertEquals(1, version.getMinorVerion());
-    assertEquals(0, version.getPatchVersion());
```
Comment (briandealwis) [inline src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionTest.java]: It's still useful for the tests to verify these fields though, right? (and ditto for the rest)

File: src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java (hunk 2 above)
Comment (chanseokoh) [reply src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java]: I was thinking of a possibility in the future another version string such as "unknown" or a commit SHA hash could be associated with the value -1. But considering that `new CloudSdkVersion("0.0.1").compareTo(new CloudSdkVersion("0.0.01")) == true`, it makes sense to drop `version` from computing the hash.

File: src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java (hunk 3 above)
Comment (chanseokoh) [reply src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java]: Yup.

File: src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionTest.java (hunk 4 above)
Comment (chanseokoh) [reply src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionTest.java]: That's true, but I don't really want to make the fields package-protected only for testing. Making a method package-protected, I'm a little bit more lenient, OTOH. We have `compareTo()` tests, so we are somewhat covered.

**Comment by chanseokoh** [comment]
Not sure why the Travis push build is failing all of a sudden. Seems unrelated.

```
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.1:report (generation) on project appengine-plugins-core: Execution generation of goal org.jacoco:jacoco-maven-plugin:0.8.1:report failed: A required class was missing while executing org.jacoco:jacoco-maven-plugin:0.8.1:report: org/apache/commons/collections/ExtendedProperties
```

File: src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionTest.java (hunk 4 above)
Comment (briandealwis) [reply src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionTest.java]: Problem is that you don't know that the parsing is correct.  Especially since `toString()` just returns the original version string.  Maybe if `toString()` computed the result then you could compare that.

Comment (chanseokoh) [reply src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionTest.java]: But the test will depend on the implementation details of `toString()`, which is exactly the current situation.

Comment (briandealwis) [reply src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionTest.java]: With your patch as is, there is no way to verify that the version parsing has correctly identified the version components.  Having `toString()` as a proxy seems ok to me if you don't want to expose `*Version` and friends as `@VisibleForTesting`.

Comment (chanseokoh) [reply src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionTest.java]: I can think of some ways to verify the version parsing indirectly. I'll add some dedicated tests.

**Comment by chanseokoh** [comment]
I still need to figure out why the Travis PR build is failing. Seems like a bug of some plugin.

**Comment by chanseokoh** [comment]
It's passing now. @briandealwis PTAL

**Comment by chanseokoh** [comment]
Fair enough. I still think the new tests are much stronger than the old test that suffers from the same pitfalls, but I've restored the old test with `@VisibleForTesting`. Not a big deal, after all.
