### PR TITLE
Fix NPE in getRuntime() when empty app.yaml

### LINKED ISSUE #405: NullPointerException from AppYaml.getRuntime()
`yamlMap` can be null [here](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/v0.3.3/src/main/java/com/google/cloud/tools/project/AppYaml.java). The problem is that `Yaml.load()` may return null [in the constructor](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/v0.3.3/src/main/java/com/google/cloud/tools/project/AppYaml.java#L45), when the `app.yaml` is completely empty for example. [The SnakeYAML Javadoc](http://javadox.com/org.yaml/snakeyaml/1.8/org/yaml/snakeyaml/Yaml.html#load(java.io.InputStream)) was not friendly enough to mention it can return null.

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #405.

### CODE REVIEW

File: src/test/java/com/google/cloud/tools/project/AppYamlTest.java [hunk 1]
```diff
@@ -52,9 +52,16 @@ public void testGetRuntime_failureBecauseNotPresent() throws IOException {
     Assert.assertNull(new AppYaml(appYaml).getRuntime());
   }
 
+  // https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/405
+  @Test
+  public void testGetRuntime_noNullPointerExceptionIfEmptyAppYaml() throws IOException {
```
Comment (elharo) [inline src/test/java/com/google/cloud/tools/project/AppYamlTest.java]: this name is a bit long. Maybe just
testGetRuntime_emptyAppYaml
