### PR TITLE
fix some errorprone warnings

### LINKED ISSUE #602: Errorprone warnings to fix
[WARNING] /Users/elharo/appengine-plugins-core/src/main/java/com/google/cloud/tools/libraries/CloudLibraries.java:[59,34] [DefaultCharset] Implicit use of the platform default charset, which can result in differing behaviour between JVM executions or incorrect behavior if the encoding of the data source doesn't match expectations.
    (see http://errorprone.info/bugpattern/DefaultCharset)
  Did you mean 'InputStreamReader reader = new InputStreamReader(inputStream, UTF_8);' or 'InputStreamReader reader = new InputStreamReader(inputStream, Charset.defaultCharset());'?
[WARNING] /Users/elharo/appengine-plugins-core/src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionPreRelease.java:[45,45] [StringSplitter] String.split(String) has surprising behavior
    (see http://errorprone.info/bugpattern/StringSplitter)
  Did you mean 'Iterable<String> segmentParts = Splitter.on('.').split(preRelease);'?
[WARNING] /Users/elharo/appengine-plugins-core/src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/StringBuilderProcessOutputLineListener.java:[23,39] [JdkObsolete] StringBuffer performs synchronization that is usually unnecessary; prefer StringBuilder.
    (see http://errorprone.info/bugpattern/JdkObsolete)
[WARNING] /Users/elharo/appengine-plugins-core/src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/LegacyProcessHandler.java:[157,17] [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace
    (see http://errorprone.info/bugpattern/CatchAndPrintStackTrace)
[WARNING] /Users/elharo/appengine-plugins-core/src/main/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdk.java:[83,13] [DefaultCharset] Implicit use of the platform default charset, which can result in differing behaviour between JVM executions or incorrect behavior if the encoding of the data source doesn't match expectations.
    (see http://errorprone.info/bugpattern/DefaultCharset)
  Did you mean 'new String(Files.readAllBytes(getSdkHome().resolve("VERSION")), UTF_8).trim();' or 'new String(Files.readAllBytes(getSdkHome().resolve("VERSION")), Charset.defaultCharset()).trim();'?
[WARNING] /Users/elharo/appengine-plugins-core/src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java:[88,39] [StringSplitter] String.split(String) has surprising behavior
    (see http://errorprone.info/bugpattern/StringSplitter)
  Did you mean 'for (String path : Splitter.on(File.pathSeparator).split(pathEnv)) {'?
[WARNING] /Users/elharo/appengine-plugins-core/src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/GcloudStructuredLog.java:[27,17] [JavaLangClash] com.google.cloud.tools.appengine.cloudsdk.serialization.GcloudStructuredLog.Error clashes with java.lang.Error

### PR DESCRIPTION
**Pull request by elharo**
@loosebazooka JSON defaults to UTF-8 fix #602

### CODE REVIEW

**Comment by elharo** [comment]
Test failure looks flaky:


Results :

Tests in error: 
  testJson(com.google.cloud.tools.libraries.LibrariesTest): Connection refused (Connection refused)

File: src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/StringBuilderProcessOutputLineListener.java [hunk 1]
```diff
@@ -20,6 +20,7 @@
 public class StringBuilderProcessOutputLineListener implements ProcessOutputLineListener {
 
   // This used to be a StringBuilder but that wasn't thread safe.
+  @SuppressWarnings("JdkObsolete")
```
Comment (loosebazooka) [inline src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/StringBuilderProcessOutputLineListener.java]: should we just fix this warning?

Comment (elharo) [reply src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/StringBuilderProcessOutputLineListener.java]: No, this is an overly aggressive warning for a case that doesn't apply here. StringBuffer is exactly what we need.
