### PR TITLE
include stderr and stdout in CommandExecutionException

### LINKED ISSUE #814: Log error on command failures (non-zero exits)
Currently, when command fails (such as `ManagedCloudSDK.isUpToDate()`) fails, there is no insight into detailed error message, even though, error message is captured in `CommandExitException`.

https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/main/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdk.java#L162

Suggest that upon `CommandExitException`, log error with high priority and/or propagate to the wrapping Exception, or, use it as part of the message of `CommandExitException`

### PR DESCRIPTION
**Pull request by elharo**
@loosebazooka @saturnism 
See https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/410

### CODE REVIEW

File: src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandExecutionException.java [hunk 1]
```diff
@@ -21,4 +21,12 @@
   public CommandExecutionException(Throwable cause) {
     super(cause);
   }
+
+  /**
+   * @param message failure details; typically output of stderr
```
Comment (chanseokoh) [inline src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandExecutionException.java]: output of stdout and stderr

File: src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandCaller.java [hunk 2]
```diff
@@ -69,7 +69,19 @@ public String call(
       }
```
Comment (chanseokoh) [inline src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandCaller.java]: This still doesn't fix #814. `CommandExitException` above should also be modified to include the stdOut and stdErr as an exception message like `CommandExecutionException` does in this PR (if this is the way we want to surface the outputs). `CommandExitException` accepts stdOut and stdErr as an argument in the constructor, but they are not set as an exception message.

Comment (elharo) [reply src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandCaller.java]: Correct. The information is in the exception, but the client needs to choose to surface that.

File: src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandCaller.java [hunk 3]
```diff
@@ -69,7 +69,19 @@ public String call(
...
+        stdOut = stdOutSaver.getResult().get();
+      } catch (InterruptedException | ExecutionException ignored) {
+        stdOut = "stdout collection interrupted";
+      }
+      try {
+        stdErr = stdErrSaver.getResult().get();
+      } catch (InterruptedException | ExecutionException ignored) {
+        stdErr = "stderr collection interrupted";
+      }
+      throw new CommandExecutionException(stdOut + "\n" + stdErr, ex);
```
Comment (saturnism) [inline src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandCaller.java]: in CommandExitException, error is stored in a separate field instead of the actual `message` field of the exception. I feel that's cleaner. I'd also suggest that stdout and stderr be kept  in 2 different fields and let the caller render it.

File: src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandCaller.java (hunk 2 above)
Comment (chanseokoh) [reply src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandCaller.java]: And this PR does not fix #814. The error in #814 is about `CommandExitException`, but this PR doesn't change anything about `CommandExitException`. I think we should let #814 open.

Comment (chanseokoh) [reply src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandCaller.java]: Resolved. I've removed "fixes #814" from your initial PR comment.

**Comment by loosebazooka** [comment]
I think it's fine... will review when I get a chance. @saturnism @chanseokoh any comments?

**Comment by chanseokoh** [comment]
Nothing much from my side besides this minor Javadoc comment: https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/816#discussion_r344307810

File: src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandExecutionException.java (hunk 1 above)
Comment (elharo) [reply src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandExecutionException.java]: done

File: src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandCaller.java (hunk 3 above)
Comment (elharo) [reply src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandCaller.java]: done
